print("To check id of any variable")
a,b=int(input("Enter first no.")),int(input("Enter second no."))
c=id(a)
d=id(b)
print("Id of 1st variable",c)
print("Id of 2nd variable",d)
e,f=input("Enter first string"),input("Enter second string")
g=id(e)
h=id(f)
print("Id of 1st variable",g)
print("Id of 2nd variable",h)
